# Dockerfile for React client in Dev

# Build react client
FROM node:20-alpine

# Working directory be app
WORKDIR /usr/app

###  Installing dependencies
COPY package*.json ./
RUN npm install

# copy local files to app folder
COPY . .

CMD ["npm","run","dev"]