version: "3"
services:
  frontend:
    container_name: ${PROJECT_NAME}-backend
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./src:/usr/app/src
      - ./public:/usr/app/public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}.entrypoints=http"
      - "traefik.http.routers.${PROJECT_NAME}.rule=Host(`${FRONTEND_DOMAIN}`)"
      - "traefik.http.middlewares.${PROJECT_NAME}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${PROJECT_NAME}.middlewares=${PROJECT_NAME}-https-redirect"
      - "traefik.http.routers.${PROJECT_NAME}-secure.entrypoints=https"
      - "traefik.http.routers.${PROJECT_NAME}-secure.rule=Host(`${FRONTEND_DOMAIN}`)"
      - "traefik.http.routers.${PROJECT_NAME}-secure.tls=true"
      - "traefik.http.routers.${PROJECT_NAME}-secure.tls.certresolver=http"
      - "traefik.http.routers.${PROJECT_NAME}-secure.service=${PROJECT_NAME}"
      - "traefik.http.services.${PROJECT_NAME}.loadbalancer.server.port=5173"
      - "traefik.docker.network=proxy"
    networks:
      - proxy

networks:
  proxy:
    external:
      name: proxy
